#ifndef _COMPONENT_TYPE_H_
#define _COMPONENT_TYPE_H_

enum class E_Component_Type
{
	E_COMPONENT_TYPE_SPRITE,
	E_COMPONENT_TYPE_ANIMATOR,

	//UI Components
	E_COMPONENT_TYPE_UI_TEXT,
	E_COMPONENT_TYPE_UI_LIST_MENU,
	E_COMPONENT_TYPE_UI_FILE_LIST_MENU,

	E_COMPONENT_TYPE_MAX,
};

#endif
