#ifndef _CONSOLE_COLOURS_H_
#define _CONSOLE_COLOURS_H

#include <Windows.h>

#define BACKGROUND_BRIGHT_RED		BACKGROUND_RED | BACKGROUND_INTENSITY
#define BACKGROUND_BRIGHT_GREEN		BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BACKGROUND_BRIGHT_BLUE		BACKGROUND_BLUE | BACKGROUND_INTENSITY

#define BACKGROUND_TURQOISE			BACKGROUND_BLUE | BACKGROUND_GREEN
#define BACKGROUND_SKYBLUE			BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BACKGROUND_PURPLE			BACKGROUND_BLUE | BACKGROUND_RED
#define BACKGROUND_PINK				BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY
#define BACKGROUND_MUSTARD			BACKGROUND_GREEN | BACKGROUND_RED
#define BACKGROUND_YELLOW			BACKGROUND_GREEN | BACKGROUND_RED | BACKGROUND_INTENSITY

#define BACKGROUND_WHITE			BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define BACKGROUND_GREY				BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE
#define BACKGROUND_DARK_GREY		BACKGROUND_INTENSITY

#define BACKGROUND_BLACK			0

#define FOREGROUND_BRIGHT_RED		FOREGROUND_RED | FOREGROUND_INTENSITY
#define FOREGROUND_BRIGHT_GREEN		FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define FOREGROUND_BRIGHT_BLUE		FOREGROUND_BLUE | FOREGROUND_INTENSITY

#define FOREGROUND_TURQOISE			FOREGROUND_BLUE | FOREGROUND_GREEN
#define FOREGROUND_SKYBLUE			FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define FOREGROUND_PURPLE			FOREGROUND_BLUE | FOREGROUND_RED
#define FOREGROUND_PINK				FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_INTENSITY
#define FOREGROUND_MUSTARD			FOREGROUND_GREEN | FOREGROUND_RED
#define FOREGROUND_YELLOW			FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY

#define FOREGROUND_WHITE			FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define FOREGROUND_GREY				FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE
#define FOREGROUND_DARK_GREY		FOREGROUND_INTENSITY

#define FOREGROUND_BLACK			0



#endif
